### ISSUE TITLE
Support CLOUDSDK_AUTH_ACCESS_TOKEN for authentication

### ISSUE THREAD

**Issue by thusithaC** [google-github-actions/setup-cloud-sdk#234]
### TL;DR

Support CLOUDSDK_AUTH_ACCESS_TOKEN

### Detailed design

The CLI supports CLOUDSDK_AUTH_ACCESS_TOKEN, but the github action and the setup-cloud-sdk does not support it (from what I've experimented). Is there a way to authenticate with the $CLOUDSDK_AUTH_ACCESS_TOKEN or any other env variables? 

### Additional information

We would like to run `google-github-actions/setup-gcloud` with CLOUDSDK_AUTH_ACCESS_TOKEN and the Project ID. Unfortunately we cannot run the auth action but have to rely on a home grown solution to obtain a short lived credential.

**Comment by sethvargo** [comment]
After you create the token in your homegrown solution, [set the environment variable](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable) before calling `setup-gcloud`.

Is that not working?

**Comment by thusithaC** [comment]
Hi @sethvargo,  We are setting `CLOUDSDK_AUTH_ACCESS_TOKEN` like you mentioned. I did some digging into the code and how gcloud behaves when a token is provided. 

in the library `isAuthenticated()` function seems to call `gcloud auth list`. This is what I get when I call that command when I run it in a different environment when `CLOUDSDK_AUTH_ACCESS_TOKEN` is set. 
```
export async function isAuthenticated(): Promise<boolean> {
  const result = await gcloudRun(['auth', 'list']);
  return !result.output.includes('No credentialed accounts.');
}
```


```
root@e05a09a86f16:/# gcloud auth list

No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`
```

However, the `print-access-token` command works, indicating that gcloud is aware of the token provided. 
```
root@e05a09a86f16:/# gcloud auth print-access-token
ya29.c.c....
```

I can also access storage buckets etc using the cli. 

```
root@e05a09a86f16:/# gcloud storage ls gs://....
gs://g....
root@e05a09a86f16:/# 
```

I'm not sure why `gcloud auth list` does not take into account that a token has been provided. Is there anything other than I can set such that the library `isAuthenticated()` function would return true?


P.S. gcloud auth command is weird. Even if I manually set the SA, I still get an error when i call `gcloud auth list`.

```
root@e05a09a86f16:/# gcloud auth list

No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`

root@e05a09a86f16:/# gcloud auth login app-xxx@projectxxx.iam.gserviceaccount.com

WARNING: Re-using locally stored credentials for [app-xxx@projectxxx.iam.gserviceaccount.com]. To fetch new credentials, re-run the command with the `--force` flag.

You are now logged in as [app-xxx@projectxxx.iam.gserviceaccount.com].
Your current project is [projectxxx].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID

root@e05a09a86f16:/# gcloud auth list

No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`

```

**Comment by sethvargo** [comment]
All of that makes sense. The Cloud SDK isn't "authenticated" as a client, you are providing it an authentication credential by proxy.

I'm still confused about the issue you're facing. Are gcloud commands not working when you set the environment variable?

**Comment by thusithaC** [comment]
@sethvargo Actually feeling quite stupid right now, I got this warning and an unrelated error down the path in the github actions, and I thought because of the auth issue gcloud is not being set up properly. 

```
Warning: The gcloud CLI is not authenticated (or it is not installed). Authenticate by adding the "google-github-actions/auth" step prior this one.
```

So in fact I could just ignore this warning and move forward! Your comment about "I'm still confused about the issue you're facing." made me retrace my steps! Thanks :)
