### ISSUE TITLE
Enable a way to override your RUNNER_TOOL_CACHE

### ISSUE THREAD

**Issue by incodemode** [google-github-actions/setup-cloud-sdk#265]
### TL;DR

You override the env RUNNER_TOOL_CACHE with a random path instead of using the original variable, this makes impositble to cache the download in github actions using actions/cache@v3 . Caching it may not sound like much time, but that saved minute is the difference between a quick debugging session and a slower one when relying on github actions to deploy to a dev environments.

### Detailed design

Make a COMPLY_WITH_RUNNER_TOOL_CACHE env or a input of the action to disable that override.

**Comment by sethvargo** [comment]
Hi @incodemode - we only override `RUNNER_TOOL_CACHE` [during testing](https://github.com/google-github-actions/setup-cloud-sdk/blob/7458dd222121d80ff6b491103733e25cbadc0be7/src/test-util.ts#L42), which is not used during runtime.

Can you share more about the problem you're experiencing?

**Comment by sethvargo** [comment]
Closing due to lack of response.
